name: Link Check

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'README.adoc'
      - 'lychee.toml'
  pull_request:
    paths:
      - 'docs/**'
      - 'README.adoc'
      - 'lychee.toml'
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --config lychee.toml --verbose --no-progress 'docs/**/*.adoc' 'docs/**/*.md' 'README.adoc'
          fail: true
          token: ${{ secrets.GITHUB_TOKEN }}
          format: markdown
          output: ./lychee/out.md

      - name: Update PR Body
        if: failure()
        uses: peter-evans/update-pr-from-file@v3
        with:
          pr-number: ${{ github.event.pull_request.number }}
          body-file: ./lychee/out.md